= Script: NVS 4
:toc:


// Metadata
:author: GeorgSeng
:date: 2019-12-07
:revision:  1.5

// Settings
:source-highlighter: coderay
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:pdfwidth: pdfwidth=80vw
// Refs:
:imagesdir: /home/georg/Documents/Data/repos/4NVS/Documents/images
//:imagesdir: images
//:sourcedir-code: src/main/java/at/htl/jdbcprimer
//:sourcedir-test: src/test/java/at/htl/jdbcprimer

 
Version: {revision}


//General

//
=== Create Project

Create *Maven* Project with Intellij.
For Example:
[source, xml]
----
    <groupId>at.htl</groupId>
    <artifactId>PersonRest</artifactId>
----

//
=== Pom.xml
.Pom.xml
[source, XML]
----
    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>

        <groupId>at.htl</groupId>
        <artifactId>vehicle</artifactId>
        <version>1.0-SNAPSHOT</version>
        <packaging>war</packaging>

                <properties>
            <maven.compiler.source>11</maven.compiler.source>
            <maven.compiler.target>11</maven.compiler.target>
        </properties>

        <dependencies>
            <dependency>
                <groupId>jakarta.platform</groupId>
                <artifactId>jakarta.jakartaee-api</artifactId>
                <version>8.0.0</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>2.3.2</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>

        <build>
            <finalName>vehicle</finalName>
        </build>


    </project>
----

.Useful Package sources
[source, XML]
----
                            <!-- Useful Sources -->
    <!-- https://mvnrepository.com/artifact/junit/junit -->
    <!-- https://mvnrepository.com/artifact/org.glassfish.jersey.core/jersey-client -->
    <!-- https://mvnrepository.com/artifact/org.glassfish.jersey.media/jersey-media-json-processing -->
    <!-- https://mvnrepository.com/artifact/org.glassfish/javax.json -->
    <!-- https://mvnrepository.com/artifact/org.glassfish.jersey.inject/jersey-hk2 -->
    <!-- https://mvnrepository.com/artifact/org.hamcrest/hamcrest -->
----

// General

include::General.adoc[]

//CDI
== CDI
=== Context Dependency Injection 
CDI is part of JavaBeans it can be configured in the beans.xml file.

With the @Inject the cdi can create a contextual instance of the Object / Class you want to have.

* Field injection type (most important): Request Context and Injected in a particular field (@Inject private RequestScope requestScop)

* Constructor injection point (Field gets initialized in the constructor using cdi):  @Inject private ScopesBean(DependentScope){this.dependentScope = dependentScope;}

* Method injection point is the same as Constructor method.


== Technologies

=== Jakarta EE
Good Source:
https://eclipse-ee4j.github.io/jakartaee-tutorial/

=== JUnit 4

.*Method Annotations*
|===
| *Tag* | *Description*
| @Test | Turns a public method into a JUnit test case.
| @Before | Method to run before every test case
| @After | Method to run after every test case
| @BeforeClass | Method to run once, before any test cases have run
| @AfterClass | Method to run once, after all test cases have run
|===

.*Assert Methods*
|===
| Method | Description
| assertTrue(test) | fails if the Boolean test is false
| assertFalse(test) | fails if the Boolean test is true
| assertEquals(expected, actual) | fails if the values are not equal
| assertSame(expected, actual) | fails if the values are not the same (by ==) have run
| assertNotSame(expected, actual) | fails if the values are the same (by ==)
| assertNull(value) | fails if the given value is not null
| assertNotNull(value) | fails if the given value is null
| fail() | causes current test to immediately fail
| assertEquals(“message”, expected, actual) | Each method can also be passed a string to display if it fails
|===

Good Source:
https://www.javatpoint.com/

== AsciiDoc

Great Source:
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

== Linux 

=== Terminal

|=== 
| *Command* | *Description*
| ll | list all files and folders
| chmod | change mode of a file
| chown | change user rights on a folder

|===

== Docker
Docker is a toll that gives you the opportunity to run applications in a small virtualization environment like a container. Docker is a major part for Microsrvices.

.Table useful commands
[options="header,footer"]
|=======================
| Command | Description
| docker ps | list running containers   
| docker inspect [container name] | list all information's about the container
|=======================


include::Hints.adoc[]

include::Persistance-with-jpa.adoc[]

include::Rest.adoc[]

include::Quarkus.adoc[]

