version: "3"

services: 
    web: 
        image: nginx:alpine
        ports: 
            - "80:80"
        volumes: 
            - ./www:/www
            - ./config/site.conf:/etc/nginx/conf.d/default.conf

    php: 
        build:
            context: ./phpDockerfile/
        ports: 
            - 9000:9000
        volumes: 
            - ./www:/www

    mariadb:
        image: mariadb
        ports: 
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: passme