version: "2"

services: 
    web: 
        image: nginx:alpine
        ports: 
            - "80:80"
        volumes: 
            - ./www:/www
            - ./config/site.conf:/etc/nginx/conf.d/default.conf